### ISSUE TITLE
Release notes have weird line breaks

### ISSUE THREAD

**Issue by TadeSF** [DeutscheModelUnitedNations/munify#181]
![CleanShot 2024-05-18 at 01 29 15@2x](https://github.com/DeutscheModelUnitedNations/munify/assets/42637916/d1ccb956-8492-4603-818e-8a4c59d75c6b)

**Comment by ahsanfarooq210** [comment]
Hi @TadeSF. I would like to work on this issue. Assign it to me

**Comment by TadeSF** [comment]
Hey @ahsanfarooq210, for sure – go ahead! Thanks for contributing! 🥳 
I suspect the Markdown rendering library to be the culprit. Maybe that needs better configuration.

And if you are very much motivated: The Markdown rendering library does not account for markdown comments. If you want, you can also implement a filter after fetching the markdown data from the github api that filters comments like this: `<!-- ... -->` e.g. `<!-- Release notes generated using configuration in .github/release.yml at main -->`
But thats only a cherry on top – you can also just leave it by fixing the width :)

Just a side-note when you get started developing: We recently restructured how we use icons in the repo – and since we are using FontAwesome pro, the files are encrypted to not run into any license issues. And since we don't have a fallback in place yet, you won't be seeing any icons. Don't be confused by that ;)

**Comment by TadeSF** [comment]
Yes! Looks perfect. Thanks alot!

And about your question: Yes, I would think so. If you dont somehow get the markdown-parser to filter out md/html-comments on its own, one would have to remove them by altering the response data.

**Comment by TadeSF** [comment]
Just out of curiousity: How did you stumble accross our project and what made you want to participate? 😊

**Comment by ahsanfarooq210** [comment]
> Just out of curiousity: How did you stumble accross our project and what made you want to participate? 😊

found it [here](https://goodfirstissues.com/index.html). This websites lists out issues with "good first issue" tag.

**Comment by ahsanfarooq210** [comment]
@TadeSF  Please review the PR
