### ISSUE TITLE
Automate prisma migrations in commit hooks & dev scripts

### ISSUE THREAD

**Issue by m1212e** [DeutscheModelUnitedNations/munify#23]
Use push & migrate commands in commit hooks and dev scripts to automate db dev workflow

**Comment by m1212e** [comment]
Add check to prevent schema drifts before commit (check if migrations dir matches current prisma schema)

precommit hooks + husky?

**Comment by m1212e** [comment]
Update: Not so sure if this is a good idea. We should investigate this

**Comment by TadeSF** [comment]
@m1212e This becomes obsolete when implementing the new backend, right?

**Comment by m1212e** [comment]
It is!
