### ISSUE TITLE
Manual tailwindcss class snippet assignments / Postcss

### ISSUE THREAD

**Issue by TadeSF** [DeutscheModelUnitedNations/munify#26]
We might need to check if postcss allows us to do this or rips out the styles it thinks we maybe dont use.

```
// queue_list.tsx
let wrapperClassNames =
    "flex-1 w-full flex gap-4 p-2 rounded-md hover:bg-white transition";

  if (countryCode === myCountry) {
    wrapperClassNames += " bg-dmunlight";
  }
```
_Originally posted by @m1212e in https://github.com/DeutscheModelUnitedNations/munify/pull/17#discussion_r1232919351_

**Comment by m1212e** [comment]
Sure!
