### ISSUE TITLE
i18n Context not working in Layout Components

### ISSUE THREAD

**Issue by TadeSF** [DeutscheModelUnitedNations/munify#41]
I18n Text cannot be used in layout components, since you cannot use contexts. That makes it not possible to have international titles for the Navbar Buttons. We should find a way to internationalise the title properties so that also the tooltips are available in all languages.

**Comment by m1212e** [comment]
Please check out the associated branch, Wouldnt that work?

**Comment by TadeSF** [comment]
Hmm, right, weird. I thought I tried that. Thanks anyway!
