### ISSUE TITLE
Popover for speakerlist controls

### ISSUE THREAD

**Issue by m1212e** [DeutscheModelUnitedNations/munify#58]

**Comment by TadeSF** [comment]
@m1212e can you elaborate what the issue exactly is?

**Comment by m1212e** [comment]
To be honest: Not really sure. I suppose its about a constant widget that floats around to present the speaker list status in all parts/screens of chase. But thats probably not relevant anymore/could be part of a retrospective improvement. Closing.

**Comment by TadeSF** [comment]
Still nice Idea though! Will keep that in mind
