### ISSUE TITLE
Weird login Button not showing in edge case

### ISSUE THREAD

**Issue by TadeSF** [DeutscheModelUnitedNations/munify#6]
What happend to our login button? :D

![grafik](https://github.com/DeutscheModelUnitedNations/munify/assets/14091540/5e3b2aa9-7ca0-4e7b-b1d4-fed8e1560554)

_Originally posted by @m1212e in https://github.com/DeutscheModelUnitedNations/munify/issues/4#issuecomment-1584264738_

**Comment by m1212e** [comment]
This can probably be closed with https://github.com/DeutscheModelUnitedNations/munify/pull/57 since we wont use the login pages
