### ISSUE TITLE
Keep chase\frontend\public\flags\rename.py

### ISSUE THREAD

**Issue by m1212e** [DeutscheModelUnitedNations/munify#9]
@TadeSF is the `chase\frontend\public\flags\rename.py` supposed to stay in the codebase? Should we set rules for helper scripts like these, e.g. what language to use/where to document and keep those?

**Comment by m1212e** [comment]
E.g. `chase/backend/build.js` is js only

**Comment by TadeSF** [comment]
No, we can totally ommit it. It is in there by mistake, because I copied the flag svgs from another project where I did a renaming of the lot with this short skript and kept it if I ever needed to recycle the skript.

I just removed it from the codebase.

Thanks for the oversight!
